version: 2
jobs:
  test:
    working_directory: ~/sivar-utils
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Validate lockfile
          command: npx lockfile-lint -p package-lock.json -t npm -a npm
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test -- --verbose
  docs-deploy:
    working_directory: ~/sivar-utils
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Config git
          command: |
            git config user.email "ci-build@sivar-utils.org"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - '48:38:cd:61:4c:91:63:58:1d:4e:ef:07:ff:8a:09:f9'
      - run:
          name: Build and deploy docs to gh-pages
          command: npm run deploy
workflows:
  version: 2
  build:
    jobs:
      - test
      - docs-deploy:
          requires:
            - test
          filters:
            branches:
              only: master
